### ISSUE TITLE
Will not migrate

### ISSUE THREAD

**Issue by amboycharlie** [django-leonardo/site-template#1]
(leonardo_venv)Tims-iMac:myproject python$ ls
README.rst  leonardo_site   manage.py
(leonardo_venv)Tims-iMac:myproject python$ python manage.py makemigrations --noinput
/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/leonardo/settings.py:73: UserWarning: leonardo_site.local.settings is obsolete use new location
  'leonardo_site.local.settings is obsolete use new location')
/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/leonardo/settings.py:90: UserWarning: local_settings was not found in $PYTHONPATH !
  'local_settings was not found in $PYTHONPATH !')
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/django/core/management/**init**.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/django/core/management/**init**.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/django/conf/**init**.py", line 48, in **getattr**
    self._setup(name)
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/leonardo/settings.py", line 123, in <module>
    leonardo.get_app_modules(APPS)
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/leonardo/base.py", line 83, in get_app_modules
    mod = import_module('.{0}'.format(app), package_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/leonardo/module/web/**init**.py", line 6, in <module>
    from .widget import *
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/leonardo/module/web/widget/**init**.py", line 4, in <module>
    from .markuptext.models import MarkupTextWidget
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/leonardo/module/web/widget/markuptext/models.py", line 5, in <module>
    from markupfield.fields import MarkupField
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/markupfield/fields.py", line 8, in <module>
    from markupfield import markup
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/markupfield/markup.py", line 70, in <module>
    from docutils.core import publish_parts
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/docutils/core.py", line 20, in <module>
    from docutils import frontend, io, utils, readers, writers
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/docutils/frontend.py", line 41, in <module>
    import docutils.utils
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/docutils/utils/**init**.py", line 20, in <module>
    import docutils.io
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/python/Repo/leonardo_venv/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by michaelkuty** [comment]
Did you try one liner script? 

```
 wget -O - https://github.com/django-leonardo/django-leonardo/raw/develop/contrib/scripts/install_leonardo.sh | sh
```

I své you havent locale UTF 8
http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8
